### PR TITLE
Darkmode background fix

### LINKED ISSUE #134: Adjust the dark-mode colours to match the spec.
**Is your improvement request related to a specific problem in the code or project structure? Please describe.** 👨‍💻
Currently, the background colours of the app is pitch black in dark mode. This does not match the spec

**Describe the improvement or refactor you would like** 🎯
The background colours in dark mode should match the spec:

Dark: 48556E
Darker: 384155
Darkest: 282F3C

image_720

**Explain why this improvement or refactor is beneficial** 🎖️
This keeps the product up to code with the expected spec.

**Additional context or comments**
Consider using the `tailwind.config` and the `global.css` to adjust the colours. __do not__ set the colours directly in the code. This should be defined in the theme - to make sure it reaches the entire project

### PR DESCRIPTION
**Pull request by hediinn**
#134 fix

### CODE REVIEW

**Comment by suuunly** [comment]
code lgtm! 
Just want a quick check from the designer, regarding the colours. 

@hannaostero, got any final notes on the colours?
Keep in mind that the navigation overlapping the header is a known bug that will be fixed in another release.

image
image

**Comment by hannaostero** [comment]
Darkmode colours lgtm!
Just have some beef with some other details ;)

**Comment by suuunly** [comment]
Sounds! good I will approve it then 👍🏻

**Review by suuunly — APPROVED** [review]

**Comment by suuunly** [comment]
@hannaostero I'll create a separate issue for the aforementioned issue with the nav bar overlapping the header 😄

**Pull request merged**
