### PR TITLE
Replace pwa logo

### PR DESCRIPTION
**Pull request by Eikaman**
Bugfix. The correct image is used for the PWA logo.

### CODE REVIEW

**Comment by suuunly** [comment]
lgtm! 😄 
@hannaostero got any final notes?
This is what the splash screen looks like now:
Photo April 13 18-08 from Google Photos

**Comment by hannaostero** [comment]
Preferably the logo should be round instead of square with rounded edges, but that's not a big deal.

**Review by suuunly — APPROVED** [review]
> Preferably the logo should be round instead of square with rounded edges, but that's not a big deal.
Sounds good. We can revisit that issue some other time if the need arises

**Comment by suuunly** [comment]
> Preferably the logo should be round instead of square with rounded edges, but that's not a big deal.

Sounds good! We will revisit that if the need arises

**Pull request merged**
